[env]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino

lib_deps =
    https://github.com/DFRobot/DFRobot_ENS160.git

[env:main]
upload_port = COM6
monitor_port = COM6
build_src_filter =
    +<main/>
    -<test_src/>
    -<information_session_src/>

[env:test]
upload_port = COM6
monitor_port = COM6
build_src_filter =
    -<main/>
    +<test_src/>
    -<information_session_src/>

[env:test_linux]
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
build_src_filter =
    -<main/>
    +<test_src/>
    -<information_session_src/>
    
[env:information]
upload_port = COM6
monitor_port = COM6
build_src_filter =
    -<main/>
    -<test_src/>
    +<information_session_src/>
